# Generated by Django 3.0.1 on 2019-12-28 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hero_name', models.CharField(max_length=20)),
                ('Hero_gender', models.BooleanField(default=False)),
                ('Hero_comment', models.CharField(max_length=128)),
                ('Hero_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.BookInfo')),
            ],
        ),
    ]
